# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import guests.models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20180709_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='invitation_id',
            field=models.CharField(db_index=True, default=guests.models._random_uuid, max_length=6, unique=True),
        ),
    ]
