# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import guests.models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_auto_20180924_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='invitation_id',
            field=models.CharField(db_index=True, default=guests.models._random_uuid, max_length=15, unique=True),
        ),
    ]
