# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0019_auto_20181118_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='interested_in_bus',
        ),
        migrations.AddField(
            model_name='party',
            name='party_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='preferred_transportation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
