# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0020_auto_20181126_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='meal',
            field=models.CharField(blank=True, choices=[('omnivore', 'I eat anything'), ('vegetarian', 'Vegetarian meal, please'), ('vegan', 'Vegan meal, please')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(choices=[('default', 'ru_joke')], max_length=10),
        ),
    ]
