# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0021_auto_20181212_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(choices=[('default', 'default'), ('ru_joke', 'ru_joke')], max_length=10),
        ),
    ]
